services:
  server:
    image: ghcr.io/gleam-lang/gleam:nightly-erlang
    command: gleam run
    ports: [ 8000:8000 ]
    volumes:
      - .:/march
      - server_build:/march/server/build
    working_dir: /march/server

  web:
    image: ghcr.io/gleam-lang/gleam:nightly-erlang
    command: gleam run -m lustre/dev start
    ports: [ 1234:1234 ]
    volumes:
      - .:/march
      - web_build:/march/web/build
    working_dir: /march/web

volumes:
  server_build:
  web_build:
