# https://gleam.run/writing-gleam/gleam-toml/

name = "main"
version = "1.0.0"
target = "javascript"
licences = ["AGPL-3.0-or-later"]

[dependencies]
api = { path = "../api" }
core = { path = "../core" }
engine = { path = "../engine" }
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.4.0 and < 6.0.0"
lustre_portal = ">= 1.0.1 and < 2.0.0"
modem = ">= 2.1.2 and < 3.0.0"
phosphor_lustre = ">= 1.0.1 and < 2.0.0"
rsvp = ">= 2.0.0 and < 3.0.0"
yuzu = { path = "../yuzu" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 2.3.4 and < 3.0.0"

[tools.lustre.html]
title = "March"
links = [{ rel = "icon", href = "/logo.svg" }]

[tools.lustre.dev]
proxy = { from = "/api", to = "http://localhost:8000/api" }
